[package]
name = "Octopus"
version = "0.1.0"
edition = "2021"
build = "build.rs"
default-run = "octopus_v3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
rand = "0.8.5"

[[bin]]
name = "octopus_v2"
path = "src/main.rs"

[[bin]]
name = "octopus_v3"
path = "src/main.rs"

[features]
nnue_level_v2 = []
nnue_level_v3 = ["nnue_level_v2"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[profile.release.build-override]
opt-level = 3
